### ISSUE TITLE
documentation training on MPII failure

### ISSUE THREAD

**Issue by estathop** [antoine77340/Mixture-of-Embedding-Experts#5]
I download both the source code and the data.zip but when tried to execute
`python train.py --epochs=50 --batch_size=512 --lr=0.0001  --coco=True`
this message appears, I guess it has something to do with the relative paths while parsing
```
python train.py --epochs=50 --batch_size=512 --lr=0.0001  --coco=True
Namespace(GPU=True, MSRVTT=False, batch_size=512, coco=True, coco_sampling_rate=1.0, epochs=50, eval_qcm=False, lr=0.0001, lr_decay=0.95, margin=0.2, model_name='test', momentum=0.9, n_cpu=1, n_display=100, optimizer='adam', seed=1, text_cluster_size=32)
Pre-loading features ... This may takes several minutes ...
Traceback (most recent call last):
  File "train.py", line 162, in <module>
    path_to_audio, mp_flow_path, mp_face_path, coco=args.coco) 
  File "/home/estathop/Mixture-of-Embedding-Experts/LSMDC.py", line 76, in __init__
    coco_visual = np.load(coco_visual_path)
  File "/home/estathop/anaconda2/envs/tensorflow/lib/python2.7/site-packages/numpy/lib/npyio.py", line 384, in load
    fid = open(file, "rb")
IOError: [Errno 2] No such file or directory: '../X_train2014_resnet152.npy
```
I tried to rename the `coco_visual_path='../X_train2014_resnet152.npy' ,coco_text_path='../w2v_coco_train2014_1.npy'` paths in LSMDC.py but with no success, any thoughts ?

**Comment by estathop** [comment]
changing the relative paths to absolute paths where the 2 files are located seem to work
