### ISSUE TITLE
Trying to use ypreds = net (text, videos, ind)

### ISSUE THREAD

**Issue by estathop** [antoine77340/Mixture-of-Embedding-Experts#8]
as said in the journal I extracted frames from a random video (25 frames per second and with standard height = 300 ) after that I passed it to a resnet152 model and extracted the 2048 feature vector from the last global average pooling layer. Results in a 1 X 2048 numpy array for one image

```
`import os
import subprocess
#from resnet_152_keras import resnet152_model
from resnet152 import ResNet152
from keras.preprocessing import image
from keras.applications.imagenet_utils import preprocess_input
import numpy as np
import pickle
from model import Net
import torch
from torch.autograd import Variable

def extract_frame(video, dst):
    '''
    Given the input video path, convert each frame of the video
    into jpg format in the destination directory.
    Args:
        video: video path
        dst: destination folder
    '''
    videoid = video.replace('.','/').split('/')
    print videoid[-2]
    with open(os.devnull, "w") as ffmpeg_log:
        command = 'ffmpeg -i ' + video + ' -r 25 ' + ' -vf scale=iw:300 '+' -f image2 ' + '{}%06d.jpg'.format(dst+videoid[-2])
        subprocess.call(command, shell=True, stdout=ffmpeg_log, stderr=ffmpeg_log)
        

extract_frame('/home/estathop/Desktop/extractim/trainvideo7011.mp4', '/home/estathop/Desktop/extractim/images/')
`

`model = ResNet152(include_top=False, weights='imagenet')
    
img_path = '/home/estathop/Desktop/extractim/images/trainvideo7011000002.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)
features2 = model.predict(x)
featurakia2 = features2[0][0][0]`
```

I also extracted text features with word2vec model pre-trained by google via gensim api which resulted in a 6 x 300 numpy array in my occasion. One row for every word. 

You mention that your model can function with some modalities missing so that's what I am trying to do.
Here is your pretrained model according to your code, being loaded

```
`video_modality_dim = {'face': (128,128), 'audio': (128*16,128),
'visual': (2048,2048), 'motion': (1024,1024)}

the_model = Net(video_modality_dim, 300, audio_cluster=16, text_cluster=32)
the_model.load_state_dict(torch.load('/home/estathop/Desktop/journalmodel/msrvttjournal.pt'))
the_model.eval()`

`word_feature_1 = wordsw2v[0]
testix = torch.from_numpy(np.array(wordsw2v[0]))
testix2 = torch.from_numpy(np.array(word_feature_1))
face_ind=np.zeros(0)
audio_ind=np.zeros(0)
motion_ind=np.zeros(0)
visual_ind= np.ones(1)
ind = {'face': face_ind, 'audio': audio_ind, 'visual': visual_ind, 'motion': motion_ind}
#torch.from_numpy(np.array([testList[1]]))
face_data = torch.from_numpy(np.empty([1,128]))

audio_data = torch.from_numpy(np.empty([1,128*16]))

motion_data =torch.from_numpy(np.empty([1,1024]))

visual_data = torch.from_numpy(np.array([featurakia2]))

text = torch.from_numpy(np.array([word_feature_1]))

audio_data = audio_data.type(torch.FloatTensor)
audio_data = Variable(audio_data, requires_grad=False)

#visual_data = torch.from_numpy(np.stack((featurakia,featurakia2)))

videos = {'face': face_data, 'audio': audio_data, 'visual': visual_data, 'motion': motion_data}

ypreds = the_model(text, videos, ind)`

```
In the code above I am building the indices accordingly with everything but `visual_ind` set to zero and `visual_ind` set to 1 for 1 feature vector. I then construct the dictionary with the data that is needed, I am trying to pass empty numpy arrays for missing modalities and the text and visual features accordingly.
when I try to `ypreds = the_model(text, videos, ind)`` the following error appears, any ideas ? I assume there is a mismatch in dimensions that I am not able to find. Any help would be appreciated

```
ypreds = the_model(text, videos, ind)
Traceback (most recent call last):

  File "<ipython-input-89-2d0cb1ee9a7e>", line 3, in <module>
    ypreds = the_model(text, videos, ind)

  File "/home/estathop/anaconda2/envs/tensorflow/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/estathop/model.py", line 39, in forward
    aggregated_video['audio'] = self.audio_pooling(video['audio'])

  File "/home/estathop/anaconda2/envs/tensorflow/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)

  File "/home/estathop/loupe.py", line 47, in forward
    assignment = assignment.view(-1, max_sample, self.cluster_size)

RuntimeError: invalid argument 2: size '[-1 x 2048 x 16]' is invalid for input with 256 elements at /opt/conda/conda-bld/pytorch_1533672544752/work/aten/src/TH/THStorage.cpp:80`
```

**Comment by antoine77340** [comment]
Hi,
Try replacing:
audio_data = torch.from_numpy(np.empty([1,128*16]))
by
audio_data = torch.from_numpy(np.empty([1,1,128]))
Audio tensor is actually of size NxTxD, where N is the batch_size, T the temporal extent of each sample and D the dimension of the audio features. I am sorry if this was not clear !

Also one thing, when you extract the resnet features, please make sure that the model is correctly on the evaluation mode by adding the line:
model.eval()
I happen to forget it once and it extracted the feature with batch norm activated (which you do not want actually).

Hope this helped you !

**Comment by estathop** [comment]
Thanks for the immediate feedback,
You must be right with `np.empty` as when I checked what the numpy array includes, it has random values.
```
empt = np.empty([1,128])

print empt
[[  4.66275287e-310   4.66277221e-310   0.00000000e+000   0.00000000e+000
    6.90121489e-310   6.90121492e-310   6.90121492e-310   6.90121491e-310
    6.90121492e-310   6.90121491e-310   6.90121494e-310   6.90121489e-310
    6.90121490e-310   6.90121491e-310   6.90121495e-310   6.90121490e-310
    6.90121495e-310   6.90121490e-310   6.90172708e-310   6.90121494e-310
    6.90121495e-310   6.90180965e-310   6.90180965e-310   6.90121493e-310
    6.90121492e-310   6.90121491e-310   6.90121492e-310   6.90121490e-310
    6.90121490e-310   6.90121494e-310   6.90121490e-310   6.90121494e-310
    6.90121494e-310   6.90121492e-310   6.90121492e-310   6.90121492e-310
    6.90121493e-310   6.90121491e-310   6.90121494e-310   6.90121489e-310
    6.90121491e-310   6.90121494e-310   6.90121492e-310   6.90121494e-310
    6.90121489e-310   6.90121493e-310   6.90121492e-310   6.90121492e-310
    6.90121491e-310   6.90121549e-310   6.90121493e-310   6.90121491e-310
    6.90121494e-310   6.90121489e-310   6.90121493e-310   6.90121489e-310
    6.90121489e-310   6.90121492e-310   6.90121492e-310   6.90121492e-310
    6.90121490e-310   6.90121491e-310   6.90121495e-310   6.90121495e-310
    6.90121490e-310   6.90121491e-310   6.90121494e-310   6.90121494e-310
    6.90121494e-310   6.90121491e-310   6.90121495e-310   6.90121492e-310
    6.90121490e-310   6.90121495e-310   6.90121493e-310   6.90121491e-310
    6.90121490e-310   6.90121493e-310   6.90121495e-310   6.90121490e-310
    6.90121493e-310   6.90121490e-310   6.90121493e-310   6.90121493e-310
    6.90121489e-310   6.90121489e-310   6.90121492e-310   6.90121492e-310
    6.90121489e-310   6.90121493e-310   6.90121495e-310   6.90121493e-310
    6.90121491e-310   6.90121494e-310   6.90121493e-310   6.90121491e-310
    6.90121489e-310   6.90121493e-310   6.90121489e-310   6.90121492e-310
    6.90121489e-310   6.90121494e-310   6.90121490e-310   6.90121494e-310
    6.90121494e-310   6.90121494e-310   6.90121489e-310   6.90121495e-310
    6.90121495e-310   6.90121493e-310   6.90121494e-310   6.90121493e-310
    6.90121492e-310   6.90121489e-310   6.90121495e-310   6.90121493e-310
    6.90121492e-310   6.90121493e-310   6.90121493e-310   6.90121495e-310
    6.90121494e-310   6.90121494e-310   6.90121549e-310   6.90121489e-310
    6.90121492e-310   6.90121491e-310   6.90121491e-310   6.90121492e-310]]
```


In the same manner as the Audio tensor includes N as the batch_size, the same applies to words embeddings, you also need there [1,6,300] to make it work. 

```
wordsw2v = pickle.load(open( "picklew2vbeforeNetVLAD.p", "rb" ))
word_feature_1 = wordsw2v[0]
wf2 = word_feature_1.reshape(1,6,300)
testix2 = torch.from_numpy(np.array(wf2))
```

The Resnet model was built and used on Keras 2.0.0 with imported weights from the initial paper, so there is no concern about model.eval() 
```

"""ResNet152 model for Keras.

# Reference:

- [Deep Residual Learning for Image Recognition](https://arxiv.org/abs/1512.03385)

Adaptation of code from flyyufelix, mvoelk, BigMoyan, fchollet

"""
```

Another thing I came across was the type of Tensor being used. When used
```
audio_data = audio_data.type(torch.FloatTensor)
audio_data = Variable(audio_data, requires_grad=False)

face_data = face_data.type(torch.FloatTensor)
face_data = Variable(face_data, requires_grad = False)

motion_data = motion_data.type(torch.FloatTensor)
motion_data = Variable(motion_data, requires_grad = False)

visual_data = visual_data.type(torch.FloatTensor)
visual_data = Variable(visual_data, requires_grad = False)
```
an error happened which asked for `torch.cuda.FloatTensor` , when I changed each type to `torch.cuda.FloatTensor` the script threw an error and asked for torch.FloatTensor. So in `model.py` I erased in 2 occasions the `.cuda()` method you had and everything worked with `torch.FloatTensor` using the CPU instead of the GPU, I guess there will be no problem in inference times.

After those tweaks I got my predictions at last, the model worked without errors. After the visual-text feature extraction and usage I am planning to fully implement your model with optical flow, face descriptors and audio. I hope everything goes well. 
Thanks for your time

**Comment by antoine77340** [comment]
I am not familiar with Keras resnet pretrained model, but to reproduce the same feature, you might want to use the Imagenet pretrained resnet-152 from pytorch model_zoo instead (the one I used):
https://pytorch.org/docs/stable/torchvision/models.html#id3

Then do not forget model.eval()
